### ISSUE TITLE
Unable to get leafmap maps in the documentation rendering from a jupyter notebook in mkdocs?

### ISSUE THREAD

**Issue by bgriffen** [opengeos/leafmap#516]
### Description

I am trying to create my own mkdocs page and all is running well. I then wanted to render the `leafmap` maps from the Jupyter notebooks [exactly as it is here](https://leafmap.org/notebooks/00_key_features/#install-leafmap). I thought by lifting the relevant parts of the `mkdocs`  yaml config for `leafmap` thinking I would be able to render Jupyter notebooks but not having any success. The text/code blocks update but no map renders.

### Source code

mkdocs.yml:
```yaml
plugins:
    - search
    - mkdocstrings
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          include_requirejs: true
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore:
              [
                  "*.ipynb",
              ]
```

Just starting with even a basic notebook import/display as follows:

![leafmap](https://github.com/opengeos/leafmap/assets/2667869/4447c0d4-41cd-4209-8743-a7d025e99859)

My result on my mkdocs page as such:

![result](https://github.com/opengeos/leafmap/assets/2667869/107dde9e-a9dc-4baf-a706-cc965dae8bf4)

Was there additional things in the `mkdocs.yml` that I'm missing or something else to get the map to display? I tried [the other feature request in 2021 related to this](https://github.com/opengeos/leafmap/issues/85) but didn't lead anywhere. Any help appreciated. Thank you.
